config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # allow all users to read all posts and comments
    can :read, Post
    can :read, Comment

    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      # can :create, Post, author_id: user.id
      # can :create, Comment, author_id: user.id
      # can :destroy, Post, author_id: user.id
      # can :destroy, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  before_save :comments_counter

  validates :text, presence: true
  def comments_counter
    post.update(comments_counter: post.comments.all.length)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  before_save :likes_counter
end

def likes_counter
  post.update(likes_counter: post.likes.all.length)
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id
  belongs_to :author, class_name: 'User'
  before_save :post_counter

  validates :title, presence: true, length: { minimum: 1, maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def post_counter
    author.update(post_counter: author.posts.all.length)
  end

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :comments, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :post_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  def most_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password photo bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to user_post_path(current_user.id, @comment.post_id), notice: 'comment posted successfully'
    else
      render :new, alert: 'Field to post comment. Please try again'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(params[:post_id]), notice: 'Comment deleted Successfully'
  end

  private

  def comment_params
    params.permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(post_id: params[:id], author: current_user)
    if @like.save
      redirect_to root_path, notice: 'Post liked'
    else
      render :new, alert: 'An error occured. Please try again'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user.id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to user_path(current_user.id), notice: 'Post saved'
    else
      render :new, alert: 'An error occured'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @posts = Post.find(params[:id])
    @post = @user.posts.find(params[:id])
    @comments = Comment.where(post_id: params[:id])
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy
    redirect_to user_path(params[:user_id]), notice: 'Post deleted Successfully'
  end

  private

  def post_params
    params.require(:post).permit(:author, :title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(author_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_with model: @comments, url: user_post_comments_path, data: {turbo: false} do |form| %>
  <div class="form__container">
    <div class="form_control">
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>

    <div>
      <%= form.submit "Post Comment" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<img class="img" src= <%= @user.photo %> alt="profile photo" /></td>
<% @user.posts.each do |post| %>
  <div class="post_body">
    <div class="inner_body">
      <p>Post #<%= post.id %></p>
      <h2><%= post.title %></h2>
      <p><%= post.text %>
    </div>
    <div class="inner_body2">
      <p>Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
    </div>
    <%= form_with url: "/users/#{@user.id}/posts/#{post.id}/likes" do |f| %>
      <%= f.submit "Like" %>
    <% end %>
  </div>
  <div class="post_body">
    <% post.comments.each do |comment| %>
      <b><%= @user.name %></b>: <%= comment.text %>
      <% if can? :manage, post %>
        <%= button_to "Delete Comment", user_post_comment_path(@user, post, comment), method: :delete, class:"delete post" %>
      <% end %>
    <% end %>
  </div>
    <%= link_to "See Post", user_post_path(post.author_id, post.id) %>
<% end %>

app/views/posts/new.html.erb
<h1>Form new </h1>

<%= form_with model: @post, url: user_posts_path, data: {turbo: false} do |form| %>
 <% if form.object.errors.any? %>
    <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
    <div><%= message %></div>
    <% end %>
    </div>
  <% end %>

  <div class="form__container">
    <div class="form_control">
      <%= form.label :title %>
      <%= form.text_field :title%>
    </div>
    <div class="form_control">
      <%= form.label :text %>
      <%= form.text_field :text %>
    </div>

    <div>
      <%= form.submit "Create Post"%>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>Posts show method</h1>

<div class="user_show_container">
  <% if can? :manage, @post %>
   <%= button_to "Delete Post", user_post_path(author_id: @user.id, post_id: @post.id), method: :delete, class:"delete post" %>
  <% end %>
  
  <div class="post_container_info">
    <h4><%= @posts.class %> #<%= @user.id %> by <%= @user.name%></h4>
    <span>Comments: <%= @posts.comments_counter%> Likes: <%= @posts.likes_counter%></span>
  </div>

  <div class="post_desc">
    <%= @posts.text%>
  </div>

  <div class="post_comment_limit post_comments">
    <% @comments.each do |comment| %>
      <p><%= comment.author.name%> : <%= comment.text%></p>
    <% end %>
  </div>

  <div>
    <button>
      <%= link_to 'Write a comment', new_user_post_comment_path(@user.id, @posts.id) %>
    </button>
  </div> 
</div>

app/views/shared/flash.html.erb
<% if flash[:notice]%>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert]%>
  <div class="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
      <table>
        <tr>
          <th><h1>ID</h1></th>
          <th><h1>Users</h1></th>
          <th><h1>Image</h1></td>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><h2><%= user.id %></h2></td>
          <td>
          <%= link_to user_path(user) do %>
            <h2><%= user.name %><br></h2>
          <% end %>
            Number of posts: <%= user.post_counter %>
          </td>
          <td><img class="user-img" src= <%= user.photo %> alt="profile photo" /></td>
        </tr>
        <% end %>
      </table>

app/views/users/show.html.erb
<h1>Users show method</h1>

<div class="user_show_container">
<img class="img" src= <%= @user.photo %> alt="profile photo" />
<div class="user_bio">
  <h3>Bio</h3>
  <p><%= @user.name %></p>
  <p><%= @user.bio %></p>
</div>

<% @posts.each do |post| %>
  <div class="post_container">
  <p><%= post.title %> </p>
  <p><%= post.text %></p>
  <div class="counters">
    <span>Comments: <%= post.comments_counter %></span> 
    <span>Posts: <%= @user.post_counter %></span> 
    <span>Likes: <%= post.likes_counter%> </span>
  </div>
  
  </div>
<% end %>

<button><%= link_to 'See all posts', user_posts_path(@user.id) %></button>
</div>